name: cache-nixos-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build-with-namespace-cache-volume:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x16-with-cache
      - nscloud-cache-size-60gb
      - nscloud-cache-tag-cache-nix

    steps:
      - uses: actions/checkout@v4

      - name: Set up Nix cache
        run: |
          sudo mkdir -p /cache/nix /nix
          sudo mount --bind /cache/nix /nix
          sudo chown runner /nix

      - uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            system-features = kvm nixos-test

      - name: Build a package
        run: |
          nix build 'nixpkgs#google-cloud-sdk'
          ls -lsah result/bin

  build-with-magic-nix-cache:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x16

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            system-features = kvm nixos-test

      - name: Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build a package
        run: |
          nix build 'nixpkgs#google-cloud-sdk'
          ls -lsah result/bin
